services:
  # Frontend React + Vite
  frontend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: marche_frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://backend:5000
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - marche-network

networks:
  marche-network:
    external: true
    name: marche-app_marche-network
