# ----------------------─
# PIPELINE FRONTEND
# INPUT  : topic Kafka "frontend-logs"
# FILTER : parse le format texte avec Grok
# OUTPUT : index Elasticsearch "logs-frontend-*"
# ----------------------─

input {
  kafka {
    bootstrap_servers => "broker-1:19092,broker-2:19092,broker-3:19092"
    topics            => ["frontend-logs"]
    group_id          => "logstash-frontend"
    auto_offset_reset => "earliest"
    codec             => json
  }
}

filter {

  # - Parse le format : [timestamp] METHOD /path STATUS DURATIONms -
  grok {
    match => {
      "message" => "\[%{TIMESTAMP_ISO8601:timestamp}\] %{WORD:method} %{URIPATH:path} %{NUMBER:status_code:int} %{NUMBER:duration_ms:int}ms"
    }
    tag_on_failure => ["_grokparsefailure_frontend"]   # tag si le format ne correspond pas
  }

  # - Convertit le timestamp extrait en vrai champ date -
  date {
    match  => ["timestamp", "ISO8601"]
    target => "@timestamp"   # remplace le @timestamp Logstash par celui du log
    remove_field => ["timestamp"]
  }

  # - Catégorise selon le status HTTP -
  if [status_code] {
    if [status_code] >= 500 {
      mutate { add_field => { "log_level" => "error" } }
    } else if [status_code] >= 400 {
      mutate { add_field => { "log_level" => "warn" } }
    } else {
      mutate { add_field => { "log_level" => "info" } }
    }
  }

  # - Ajoute les métadonnées de la pipeline -
  mutate {
    add_field => {
      "source_pipeline" => "frontend"
      "environment"     => "production"
    }
    # Nettoyage des champs inutiles ajoutés par Filebeat/Kafka
    remove_field => ["@version", "agent", "ecs", "input", "log", "event"]
  }

}

output {
  elasticsearch {
    hosts    => ["https://es01:9200"]
    user     => "elastic"
    password => "${ELASTIC_PASSWORD}"
    ssl_verification_mode => "none"
    index    => "logs-frontend-%{+yyyy.MM.dd}"
  }
}