services:
  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      # - Connexion Elasticsearch -
      - ELASTICSEARCH_HOSTS=https://es01:9200     # nom du conteneur ES master
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}

      # - TLS sans vérification CA -
      - ELASTICSEARCH_SSL_VERIFICATIONMODE=none

      # - Chiffrement interne Kibana -
      - XPACK_SECURITY_ENCRYPTIONKEY=${ENCRYPTION_KEY}
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${ENCRYPTION_KEY}
      - XPACK_REPORTING_ENCRYPTIONKEY=${ENCRYPTION_KEY}

      # - Identification du serveur -
      - SERVER_NAME=kibana
      - SERVER_HOST=0.0.0.0

    networks:
      - elk-net 

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

networks:
  elk-net:
    external: true