FROM node:20-alpine

WORKDIR /app

# Dépendances (cache Docker)
COPY package*.json ./
RUN npm ci --omit=dev

# Copier le code source
COPY prisma ./prisma
COPY src ./src

# Dossier uploads images
RUN mkdir -p images/uploads

# Générer le client Prisma
RUN npx prisma generate

EXPOSE 5000

CMD ["node", "src/server.js"]
