FROM node:20-alpine

WORKDIR /app

# Dépendances (cache Docker)
COPY package*.json ./
RUN npm ci --omit=dev

# Copier le code source
COPY prisma ./prisma
COPY src ./src
COPY entrypoint.sh ./entrypoint.sh

# Dossier uploads images
RUN mkdir -p images/uploads

# Générer le client Prisma
RUN npx prisma generate

# Rendre le script exécutable
RUN chmod +x entrypoint.sh

EXPOSE 5000

ENTRYPOINT ["sh", "entrypoint.sh"]
