filebeat.inputs:
  - type: container
    paths:
      - '/var/lib/docker/containers/*/*.log'

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

  - decode_json_fields:
      fields: ["message"]
      target: "json"
      overwrite_keys: true

output.elasticsearch:
  hosts: ["${ELASTIC_HOSTS}"]
  protocol: "https"
  username: "${ELASTIC_USER}"
  password: "${ELASTIC_PASSWORD}"
  ssl:
    certificate_authorities: ["/usr/share/filebeat/certs/ca/ca.crt"]

setup.kibana:
  host: "${KIBANA_HOSTS}"

logging.json: true
logging.metrics.enabled: false